### ISSUE TITLE
Feature request: search for typescript compiler in parent directories

### ISSUE THREAD

**Issue by scriby** [kotas/gulp-tsc#15]
The feature where gulp-tsc will use the typescript compiler in node_modules is helpful in the case that different projects are using different versions of typescript (I'm in this situation).

In my case, it would also be helpful if instead of just searching for typescript in the ./node_modules it would also search in ../node_modules, ../../node_modules, etc.

What do you think?

Thanks,

Chris

**Comment by kotas** [comment]
Ah yes, I think it would be great to follow the require.resolve() rule of node.js.

I'll work on it. :)

**Comment by kotas** [comment]
I've published gulp-tsc v0.5.0 which searches for typescript module based on [require resolution rule of node.js](http://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders).

I hope you'd like it. :smiley: 

Thank you for your proposal!

**Comment by scriby** [comment]
Thanks!
