### ISSUE TITLE
Default option for "target" appears to be ES3, not ES5 as documented

### ISSUE THREAD

**Issue by nzbart** [kotas/gulp-tsc#19]
The Readme states that the default value for `options.target` is ES5, but when I run gulp, the argument passed to `tsc` is in fact `--target ES3`.

If I specify ES5 explicitly, this is passed correctly to tsc.

**Comment by kotas** [comment]
Yes, ES3 is a default as tsc is, and the Readme is wrong. I'll fix it.

Thank you for pointing it out!

**Comment by kotas** [comment]
Fixed in master. I'll close this issue.
