### ISSUE TITLE
There's no way to specify flags such as --emitDecoratorMetadata

### ISSUE THREAD

**Issue by codependent** [kotas/gulp-tsc#51]
I am using gulp-tsc to compile TypeScript files in an Angular 2 application. According to Angular's doc the files must be generated with the following line:

`tsc --watch -m commonjs -t es5 --emitDecoratorMetadata file.ts`

My gulpfile.js file is as follows:

```
gulp.task('compile-ts', function(){
  return gulp.src(['resources/angular/**/*.ts'])
    .pipe(typescript({target : "ES5", module : "commonjs" }))
    .pipe(gulp.dest('./public/angular/'))
    .pipe(plugins.livereload());
});
```

It supports specifying ES5 and commonjs but there's no way to add the flag `--emitDecoratorMetadata`

**Comment by kant2002** [comment]
I accept your pull request and publsh new version of package. Enjoy :smile:

**Comment by codependent** [comment]
Thanks! ;)
